import { StyleSheet, Dimensions } from "react-native";

export const stylesheet = StyleSheet.create({
  styleChooseConsultationFormat: {
    position: "absolute",
    left: 40,
    top: 207,
    width: 159,
    color: "rgba(0,0,0,1)",
    fontSize: 24,
    letterSpacing: 0,
    fontStyle: "normal",
    textAlign: "left",
  },
  styleRectangle31: {
    position: "absolute",
    left: 40,
    top: 316,
    width: 287,
    height: 103,
    borderRadius: 16,
    backgroundColor: "#BED8FF",
  },
  styleRectangle32: {
    position: "absolute",
    left: 0,
    right: 0,
    height: 800,
    width: 360,
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#F5FCFF",
  },
  styleVector: {
    position: "absolute",
    left: 0,
    right: -57,
    top: 0,
    width: "auto",
    height: "auto",
  },
  styleZondiconsConversation: {
    position: "absolute",
    left: 73,
    top: 346,
    width: 57,
    height: 57,
  },
  styleImage: {
    position: "absolute",
    left: 73,
    top: 346,
    width: 57,
    height: 57,
  },
  styleStartConversation: {
    position: "absolute",
    left: 160,
    top: 351,
    width: 121,
    color: "rgba(0,0,0,5)",
    fontSize: 18,
    letterSpacing: 0,
    fontStyle: "normal",
    textAlign: "left",
  },
  styleVectorCopy1: {
    position: "absolute",
    left: 8,
    top: 6,
    bottom: -6,
    width: "auto",
    height: "auto",
  },
  styleMaterialSymbolNavigateNext: {
    position: "absolute",
    left: 17,
    top: 8,
    width: 45,
    height: 45,
  },
  styleVectorCopy2: {
    position: "absolute",
    left: 16,
    right: 2,
    top: 11,
    bottom: -12,
    width: "auto",
    height: "auto",
  },
  styleMaterialSymbolNavigateNextCopy1: {
    position: "absolute",
    left: 17,
    top: 8,
    width: 45,
    height: 45,
  },
  styleStyleName: {
    position: "absolute",
    width: Dimensions.get("window").width,
    height: 800,
    backgroundColor: "rgba(255,255,255,1)",
  },
});
