import { StyleSheet } from "react-native";

export const stylesheet = StyleSheet.create({
  styleRectangle22: {
    position: "absolute",
    left: 0,
    top: 0,
    width: 360,
    height: 800,
    backgroundColor: "#D3D3D3",
  },

  styleRectangle19: {
    position: "absolute",
    left: 0,
    top: 0,
    width: 360,
    height: 293,
    borderTopLeftRadius: 21,
    borderTopRightRadius: 21,
    backgroundColor: "#ADD8E6",
  },

  styleRectangle20: {
    position: "absolute",
    left: 16,
    top: 37,
    borderRadius: 16,
    width: 150,
    height: 160,
  },

  styleDrLarryA: {
    position: "absolute",
    right: 100,
    top: 60,
    width: 100,
    color: "rgba(0, 0, 0, 1)",
    fontSize: 19,
    letterSpacing: 0,
    fontStyle: "normal",
    textAlign: "left",
  },

  styleNeurologist: {
    position: "absolute",
    right: 127,
    top: 89,
    width: 73,
    colon: "rgba(0, 0, 0, 1)",
    fontSize: 13,
    letterSpacing: 0,
    fontStyle: "normal",
    textAlign: "left",
  },

  styleLosAngelesUs: {
    position: "absolute",
    right: 103,
    top: 117,
    width: 95,
    colon: "rgba(0, 0, 0, 1)",
    fontSize: 12,
    letterSpacing: 0,
    fontStyle: "normal",
    textAlign: "left",
  },

  styleVector: {
    position: "absolute",
    left: 1,
    right: -18,
    top: 1,
    bottom: -17,
    width: "auto",
    height: "auto",
  },

  styleVectorCopyl: {
    position: "absolute",
    left: 10,
    right: 8,
    top: 2,
    bottom: -3,
    width: "auto",
    height: "auto",
  },

  styleVectorCopy2: {
    position: "absolute",
    left: 13,
    right: 8,
    top: 8,
    bottom: 5,
    width: "auto",
    height: "auto",
  },

  styleNotoStar: {
    position: "absolute",
    right: 128,
    top: 169,
    width: 20,
    height: 20,
  },

  style5Star: {
    position: "absolute",
    right: 150,
    top: 153,
    width: 36,
    colon: "rgba(0, 0, 0, 1)",
    fontSize: 12,
    letterSpacing: 0,
    fontStyle: "normal",
    textAlign: "left",
  },

  styleRectangle21: {
    position: "absolute",
    right: 62,
    top: 163,
    width: 94,
    height: 35,
    borderRadius: 16,
  },

  style100Reviews: {
    position: "absolute",
    left: 37,
    top: 244,
    width: 69,
    color: "rgba(0, 0, 0, 1)",
    fontSize: 17,
    letterSpacing: 0,
    fontStyle: "normal",
    textAlign: "left",
  },

  style10YearsExp_: {
    position: "absolute",
    left: 145,
    top: 244,
    width: 86,
    color: "rgba(0, 0, 0, 1)",
    fontSize: 17,
    letterSpacing: 0,
    fontStyle: "normal",
    textAlign: "left",
  },

  style1500Patients: {
    position: "absolute",
    right: 85,
    top: 244,
    width: 68,
    color: "rgba(0, 0, 0, 1)",
    fontSize: 17,
    letterSpacing: 0,
    fontStyle: "normal",
    textAlign: "left",
  },

  styleDemography: {
    position: "absolute",
    left: 25,
    top: 328,
    width: 116,
    color: "rgba(0, 0, 0, 1)",
    fontSize: 18,
    letterSpacing: 0,
    fontStyle: "normal",
    textAlign: "left",
  },

  styleDitarry: {
    position: "absolute",
    left: 29,
    top: 366,
    width: 309,
    color: "rgba(0, 0, 0, 1)",
    fontSize: 14,
    letterSpacing: 0,
    fontStyle: "normal",
    textAlign: "left",
  },

  styleSchedules: {
    position: "absolute",
    left: 25,
    top: 435,
    width: 95,
    color: "rgba(0, 0, 0, 1)",
    fontSize: 18,
    letterSpacing: 0,
    fontStyle: "normal",
    textAlign: "left",
  },

  styleRectangle23: {
    position: "absolute",
    left: 29,
    top: 485,
    width: 58,
    height: 80,
    borderRadius: 17,
    backgroundColor: "#FFFFFF",
  },

  styleMon: {
    position: "absolute",
    left: 39,
    top: 495,
    width: 37,
    color: "rgba(0, 0, 0, 1)",
    fontSize: 16,
    letterSpacing: 0,
    fontStyle: "normal",
    textAlign: "left",
  },

  style11: {
    position: "absolute",
    left: 43,
    top: 525,
    width: 22,
    color: "rgba(0, 0, 0, 1)",
    fontSize: 20,
    letterSpacing: 0,
    fontStyle: "normal",
    textAlign: "left",
  },

  styleRectangle24: {
    position: "absolute",
    left: 101,
    top: 485,
    width: 58,
    height: 80,
    borderRadius: 17,
    backgroundColor: "#FFFFFF",
  },

  styleTue: {
    position: "absolute",
    left: 113,
    top: 495,
    width: 32,
    color: "rgba(0, 0, 0, 1)",
    fontSize: 16,
    letterSpacing: 0,
    fontStyle: "normal",
    textAlign: "left",
  },

  style12: {
    position: "absolute",
    left: 117,
    top: 525,
    width: 47,
    color: "rgba(0, 0, 0, 1)",
    fontSize: 20,
    letterSpacing: 0,
    fontStyle: "normal",
    textAlign: "left",
  },

  styleRectangle25: {
    position: "absolute",
    left: 173,
    top: 486,
    width: 58,
    height: 80,
    borderRadius: 17,
    backgroundColor: "#ADD8E6",
  },

  styleWed: {
    position: "absolute",
    left: 182,
    top: 495,
    width: 38,
    color: "rgba(0, 0, 0, 1)",
    fontSize: 16,
    letterSpacing: 0,
    fontStyle: "normal",
    textAlign: "left",
  },

  style13: {
    position: "absolute",
    left: 186,
    top: 525,
    width: 47,
    color: "rgba(0, 0, 0, 1)",
    fontSize: 20,
    letterSpacing: 0,
    fontStyle: "normal",
    textAlign: "left",
  },

  styleRectangle26: {
    position: "absolute",
    left: 243,
    top: 486,
    width: 58,
    height: 80,
    borderRadius: 17,
    backgroundColor: "#FFFFFF",
  },

  styleThur: {
    position: "absolute",
    left: 253,
    top: 495,
    width: 47,
    color: "rgba(0, 0, 0, 1)",
    fontSize: 16,
    letterSpacing: 0,
    fontStyle: "normal",
    textAlign: "left",
  },

  style14: {
    position: "absolute",
    left: 257,
    top: 525,
    width: 47,
    color: "rgba(0, 0, 0, 1)",
    fontSize: 20,
    letterSpacing: 0,
    fontStyle: "normal",
    textAlign: "left",
  },

  styleRectangle27: {
    position: "absolute",
    left: 317,
    top: 486,
    width: 58,
    height: 80,
    borderRadius: 17,
    backgroundColor: "#FFFFFF",
  },

  styleFri: {
    position: "absolutes",
    left: 327,
    top: 525,
    width: 47,
    color: "rgba(0, 0, 0, 1)",
    fontSize: 16,
    letterSpacing: 0,
    fontStyle: "normal",
    textAlign: "left",
  },

  style15: {
    position: "absolutes",
    left: 337,
    top: 525,
    width: 47,
    color: "rgba(0, 0, 0, 1)",
    fontSize: 20,
    letterSpacing: 0,
    fontStyle: "normal",
    textAlign: "left",
  },

  styleChooseTime: {
    position: "absolute",
    left: 29,
    top: 603,
    width: 118,
    color: "rgba(0, 0, 0, 1)",
    fontSize: 18,
    letterSpacing: 0,
    fontStyle: "normal",
    textAlign: "left",
  },

  styleRectangle28: {
    position: "absolute",
    left: 27,
    top: 663,
    width: 103,
    height: 38,
    borderRadius: 16,
    backgroundColor: "#FFFFFF",
  },

  style0900Am: {
    position: "absolute",
    left: 45,
    top: 673,
    width: 69,
    color: "rgba(0, 0, 0, 1)",
    fontSize: 14,
    letterSpacing: 0,
    fontStyle: "normal",
    textAlign: "left",
  },

  styleRectangle29: {
    position: "absolute",
    left: 150,
    top: 663,
    width: 103,
    height: 38,
    borderRadius: 16,
    backgroundColor: "#FFFFFF",
  },

  style1000Am: {
    position: "absolute",
    left: 171,
    top: 673,
    width: 67,
    color: "rgba(0, 0, 0, 1)",
    fontSize: 14,
    letterSpacing: 0,
    fontStyle: "normal",
    textAlign: "left",
  },

  styleRectangle30: {
    position: "absolute",
    left: 269,
    top: 663,
    width: 103,
    height: 38,
    borderRadius: 16,
    backgroundColor: "#FFFFFF",
  },

  style1100Am: {
    position: "absolute",
    left: 292,
    top: 673,
    width: 64,
    color: "rgba(0, 0, 0, 1)",
    fontSize: 14,
    letterSpacing: 0,
    fontStyle: "normal",
    textAlign: "left",
  },

  styleRectangle6: {
    position: "absolute",
    left: 85,
    top: 736,
    width: 193,
    height: 42,
    borderRadius: 16,
    backgroundColor: "#ADD8E6",
  },
  styleBookAppointment: {
    position: "absolute",
    left: 108,
    top: 746,
    width: 139,
    color: "rgba(0, 0, 0, 1)",
    fontSize: 15,
    letterSpacing: 0,
    fontStyle: "normal",
    textAlign: "center",
  },

  styleVector: {
    position: "absolute",
    left: 8,
    right: 1,
    top: 7,
    bottom: -7,
    width: "auto",
    height: "auto",
  },

  styleMaterialSymbolsNavigateNext: {
    position: "absolute",
    left: 249,
    top: 741,
    width: 24,
    height: 28,
  },
});
