import { StyleSheet } from "react-native";
export const stylesheet = StyleSheet.create({
  styleRectangle33: {
    position: "absolute",
    left: 0,
    top: 0,
    width: 360,
    height: 800,
    backgroundColor: "#F4F1F1",
  },
  styleRectangle10: {
    position: "absolute",
    right: 6,
    top: 124,
    width: 59,
    height: 48,
    borderRadius: 16,
    backgroundColor: "#0F0",
  },
  styleDoctor: {
    position: "absolute",
    left: 133,
    top: 49,
    width: 96,
    height: 800,
    color: "rgba(0,0,0,1)",
    fontSize: 24,
    fontWeight: "bold",
    fontStyle: "normal",
    textAlign: "left",
    letterSpacing: 0,
  },
  styleRectangle9: {
    position: "absolute",
    left: 40,
    top: 120,
    width: 239,
    height: 52,
    borderRadius: 50,
    backgroundColor: "#0F0",
  },
  styleSearchDoctor: {
    position: "absolute",
    left: 40,
    top: 234,
    width: 253,
    color: "rgba(0, 0, 0, 1)",
    fontSize: 24,
    fontWeight: "bold",

    letterSpacing: 0,
    fontStyle: "normal",
    textAlign: "left",
  },
  styleRectangle36: {
    position: "absolute",
    left: 40,
    top: 303,
    width: 54,
    height: 44,
    borderRadius: 16,
    backgroundColor: "#0f0",
  },
  styleAll: {
    position: "absolute",
    left: 57,
    top: 314,
    width: 24,
    color: "rgba(0, 0, 0, 1)",
    fontSize: 19,
    letterSpacing: 0,
    fontStyle: "normal",
    backgroundColor: "#0F0",
  },
  styleRectangle37: {
    position: "absolute",
    left: 111,
    top: 303,
    width: 131,
    height: 44,
    borderRadius: 16,
    backgroundColor: "#0f0",
  },
  styleCardiologist: {
    position: "absolute",
    left: 124,
    top: 314,
    width: 110,
    color: "rgba(0, 0, 0, 1)",
    fontSize: 19,
    letterSpacing: 0,
    fontStyle: "normal",
    textAlign: "left",
  },
  styleGynacologistCopy1: {
    position: "absolute",
    left: 167,
    top: 576,
    width: 96,
    color: "rgba(0, 0, 0, 1)",
    fontSize: 14,
    letterSpacing: 0,
    fontStyle: "normal",
    textAlign: "left",
  },
  stylePaediatrician: {
    position: "absolute",
    right: -33,
    top: 314,
    width: 119,
    colon: "rgba(0, 0, 0, 1)",
    fontSize: 19,
    letterSpacing: 0,
    fontStyle: "normal",
    textAlign: "left",
  },
  styleRectangle40: {
    position: "absolute",
    right: -30,
    top: 303,
    width: 131,
    height: 44,
    borderRadius: 16,
    backgroundColor: "#0f0",
  },
  styleRectangle41: {
    position: "absolute",
    left: 40,

    top: 382,

    width: 292,
    height: 418,
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    backgroundColor: "#0F0",
  },
  styleDrPeterSamuel: {
    position: "absolute",
    left: 166,

    top: 419,

    width: 146,
    color: "rgba(0,0,0,1)",
    fontSize: 18,
    letterSpacing: 0,
    fontStyle: "normal",
    textAlign: "left",
  },

  styleDrSusanParker: {
    position: "absolute",
    left: 167,

    top: 677,

    width: 146,
    color: "rgba(0,0,0,1)",
    fontSize: 18,
    letterSpacing: 0,
    fontStyle: "normal",
    textAlign: "left",
  },
  stylePaediatrician1: {
    position: "absolute",
    left: 166,

    top: 705,

    width: 87,
    color: "rgba(0,0,0,1)",
    fontSize: 14,
    letterSpacing: 0,
    fontStyle: "normal",
    textAlign: "left",
  },

  styleCardiologist2: {
    position: "absolute",
    left: 166,

    top: 447,

    width: 81,
    color: "rgba(0,0,0,1)",
    fontSize: 14,
    letterSpacing: 0,
    fontStyle: "normal",
    textAlign: "left",
  },

  stylefivestar: {
    position: "absolute",
    left: 195,

    top: 476,

    width: 40,
    color: "rgba(0,0,0,1)",
    fontSize: 14,
    letterSpacing: 0,
    fontStyle: "normal",
    textAlign: "left",
  },
  stylefivestar2: {
    position: "absolute",
    left: 196,

    top: 605,

    width: 40,
    color: "rgba(0,0,0,1)",
    fontSize: 14,
    letterSpacing: 0,
    fontStyle: "normal",
    textAlign: "left",
  },
  stylefivestar1: {
    position: "absolute",
    left: 196,

    top: 605,

    width: 40,
    color: "rgba(0,0,0,1)",
    fontSize: 14,
    letterSpacing: 0,
    fontStyle: "normal",
    textAlign: "left",
  },
  styleDanielBrayen: {
    position: "absolute",
    left: 167,

    top: 548,

    width: 150,
    color: "rgba(0,0,0,1)",
    fontSize: 18,
    letterSpacing: 0,
    fontStyle: "normal",
    textAlign: "left",
  },
  styleRectangle42: {
    position: "absolute",
    left: 66,
    top: 410,
    width: 120,
    height: 96,
    borderTopLeftRadius: null,
  },
  styleSearch: {
    position: "absolute",
    left: 94,
    top: 136,
    width: 55,
    color: "rgba(0, 0, 0, 1)",
    fontSize: 17,
    letterSpacing: 0,
    fontStyle: "normal",
    textAlign: "left",
  },
  styleDoctor: {
    position: "absolute",
    left: 133,
    top: 49,
    width: 96,
    color: "rgba(0, 0, 0, 1)",
    fontSize: 24,

    letterSpacing: 0,
    fontStyle: "normal",
    textAlign: "left",
  },
});
