import { StyleSheet, Dimensions } from "react-native";
export const stylesheet = StyleSheet.create({
  styleRectangle1: {
    position: "absolute",
    top: 0,
    left: 0,
    width: 360,
    height: 800,
    backgroundColor: "rgba(0.3,0.2,0.1,0.1)",
  },
  styleRectangle2: {
    position: "absolute",
    left: 0,
    top: 0,
    width: 360,
    height: 800,
    backgroundColor: "#000",
  },

  styleChooseFormat: {
    position: "absolute",
    left: 20,
    top: 119 - 69,
    width: 179,
    color: "rgba(0, 0, 0, 1)",
    fontSize: 20,
    letterSpacing: 0,
    fontStyle: "normal",
    textAlign: "left",
    height: "auto",
    lineHeight: 24.2,
  },
  styleRectangle2: {
    position: "absolute",
    right: 30,
    top: 114 - 69,
    width: 72,
    height: 23,
    borderRadius: 6,
    backgroundColor: "rgba(255,255,255,1)",
  },
  styleSkip: {
    position: "absolute",
    right: 50,
    top: 119 - 69,
    width: 30,
    color: "rgba(0, 0, 0, 1)",
    fontSize: 14,
    letterSpacing: 0,
    fontStyle: "normal",
    textAlign: "left",
    height: "auto",
    lineHeight: 16.9,
  },
  styleRectangle3: {
    position: "absolute",
    left: 29,
    top: 187 - 69,
    width: 302,
    height: 269,
    borderRadius: 24,
    backgroundColor: "rgba(255,255,255,1)",
  },
  styleRectangle5: {
    position: "absolute",
    left: 29,
    top: 501 - 69,
    width: 302,
    height: 269,
    borderRadius: 24,
    backgroundColor: "rgba(255,255,255,1)",
  },
  styleOnlineConsultation: {
    position: "absolute",
    left: 116,
    top: 205 - 69,
    width: 129,
    color: "rgba(0, 0, 0, 1)",
    fontSize: 20,
    letterSpacing: 0,
    fontStyle: "normal",
    textAlign: "center",
    height: "auto",
    lineHeight: 24.2,
  },
  styleEllipse5: {
    position: "absolute",
    left: 143,
    top: 265 - 69,
    borderRadius: "50%",
    width: 73,
    height: 73,
    backgroundColor: "#F24E1E",
  },
  styleEllipse6: {
    position: "absolute",
    left: 143,
    top: 579 - 69,
    borderRadius: "50%",
    width: 73,
    height: 73,
    backgroundColor: "#000",
  },
  styleEllipse7: {
    position: "absolute",
    left: 159,
    top: 595 - 69,

    width: 48,
    height: 48,
    backgroundColor: "rgba(0,0,0,0)",
  },
  styleStartingFrom50: {
    position: "absolute",
    left: 123,
    top: 346 - 69,
    width: 116,
    color: "rgba(242, 78, 30, 1)",
    fontSize: 13,
    letterSpacing: 0,
    fontStyle: "normal",
    textAlign: "center",
    height: "auto",
    lineHeight: 15.7,
  },
  styleStartingFrom50Copy1: {
    position: "absolute",
    left: 123,
    top: 669 - 69,
    width: 116,
    color: "rgba(0, 0, 0, 1)",
    fontSize: 13,
    letterSpacing: 0,
    fontStyle: "normal",
    textAlign: "center",
    height: "auto",
    lineHeight: 15.7,
  },
  styleRectangle4: {
    position: "absolute",
    left: 102,
    top: 379 - 69,
    width: 156,
    height: 42,
    borderRadius: 16,
    backgroundColor: "#F24E1E",
  },
  styleRectangle6: {
    position: "absolute",
    left: 83,
    top: 702 - 69,
    width: 193,
    height: 42,
    borderRadius: 16,
    backgroundColor: "rgba(0,0,0,1)",
  },
  styleFindDoctor: {
    position: "absolute",
    left: 143,
    top: 393 - 69,
    width: 76,
    color: "rgba(0, 0, 0, 1)",
    fontSize: 13,

    letterSpacing: 0,
    fontStyle: "normal",
    textAlign: "center",
  },
  styleVector: {
    position: "absolute",
    left: 8,
    right: 1,
    top: 6 - 69,
    bottom: -6 + 69,
    width: "auto",
    height: "auto",
  },
  styleMaterialSymbolsNavigateNext: {
    position: "absolute",
    left: 219,
    top: 389 - 69,
    width: 24,
    height: 24,
  },
  styleVisitADoctor: {
    position: "absolute",
    left: 100,
    top: 530 - 69,
    width: 150,
    color: "rgba(0, 0, 0, 1)",
    fontSize: 20,
    letterSpacing: 0,
    fontStyle: "normal",
    textAlign: "center",
    height: "auto",
    lineHeight: 24.2,
  },
  styleVectorCopy1: {
    position: "absolute",
    left: 4,
    right: -39,
    top: 4 - 69,
    bottom: -34 + 69,
    width: "auto",
    height: "auto",
  },
  styleMaterialSymbolsStethoscope: {
    position: "absolute",
    left: 154,
    top: 593 - 69,
    width: 52,
    height: 46,
  },
  styleVectorCopy2: {
    position: "absolute",
    left: 7,
    right: -24,
    top: 2 - 69,
    bottom: -37 + 69,
    width: "auto",
    height: "auto",
  },
  styleMaterialSymbolsMobileFriendlyRounded: {
    position: "absolute",
    left: 165,
    top: 280 - 69,
    width: 42,
    height: 42,
    backgroundColor: "rgba(0,0,0,0)",
  },
  styleBookAppointment: {
    position: "absolute",
    left: 102,
    top: 712 - 69,
    width: 139,
    color: "rgba(255, 255, 255, 1)",
    fontSize: 15,
    letterSpacing: 0,
    fontStyle: "normal",
    textAlign: "center",
    height: "auto",
    lineHeight: 18.2,
  },
  styleVectorCopy3: {
    position: "absolute",
    left: 8,
    right: 1,
    top: 7 - 69,
    bottom: -7 + 69,
    width: "auto",
    height: "auto",
  },
  styleMaterialSymbolsNavigateNextCopy1: {
    position: "absolute",
    left: 243,
    top: 707 - 69,
    width: 24,
    height: 28,
    backgroundColor: "#fff",
  },
  styleRectangle7: {
    position: "absolute",
    right: 43,
    top: 12 - 69,
    borderRadius: 13,
    width: 80,
    height: 52,
  },
  styleStylename: {
    position: "relative",
    width: Dimensions.get("window").width,
    height: 800,
    backgroundColor: "rgba(255, 255, 255, 1)",
  },
});
